name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
  nix:
    name: Build & Test
    strategy:
      matrix:
        system:
          - runs-on: ubuntu-24.04
            nix-system: x86_64-linux
          - runs-on: ubuntu-24.04-arm
            nix-system: aarch64-linux
    runs-on: ${{ matrix.system.runs-on }}
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5

        # This breaks bwrap in Ubuntu 24 ðŸ¦¼
      - name: Disable AppArmor restrictions
        run: |
          sysctl kernel.apparmor_restrict_unprivileged_userns
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          use-flakehub: false

      - name: Check flake
        run: nix flake check --system ${{ matrix.system.nix-system }}

      - name: Build
        run: nix build .#dykwabi --system ${{ matrix.system.nix-system }}
